### ISSUE TITLE
npm run rpc后报错

### ISSUE THREAD

**Issue by shenlq** [eggjs/egg-rpc-generator#6]
PluginSequencifyError: sequencify plugins has problem, missing: [rpc], recursive: []
	>> Plugin [rpc] is disabled or missed, but is required by [sofaRpc]

**Comment by yuchenzhen** [comment]
这个现在还是会报错的， 
在 package.json 里面 加上 下面这个就不会了
```
"egg": {
    "framework": "sofa-node"
  },
```
这个问题现在修复了吗

**Comment by gxcsoccer** [comment]
@yuchenzhen 确实要加上 framework 配置，不然不会使用 sofa-node 框架的插件配置。
